=== FlowFans/flow-token-list/src/schemas/token.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "src/schemas/token.schema.json",
  "type": "object",
  "description": "Metadata for a single token in a token list",
  "additionalProperties": false,
  "examples": [
    {
      "address": "0x1654653399040a61",
      "contractName": "FlowToken",
      "path": {
        "vault": "/storage/flowTokenVault",
        "balance": "/public/flowTokenBalance",
        "receiver": "/public/flowTokenReceiver"
      },
      "symbol": "FLOW",
      "name": "Flow",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FLOW/logo.svg",
      "tags": ["utility-token"],
      "extensions": {
        "website": "https://www.onflow.org",
        "twitter": "https://twitter.com/flow_blockchain",
        "discord": "http://discord.gg/flow"
      }
    }
  ],
  "definitions": {
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 50,
      "pattern": "^[\\-\\w]+$",
      "examples": ["compound", "stablecoin"]
    }
  },
  "properties": {
    "address": {
      "description": "The contract address",
      "examples": ["0x1654653399040a61"],
      "pattern": "^0x[0-9a-f]{16}$",
      "type": "string"
    },
    "contractName": {
      "description": "The name of the token contract",
      "examples": ["FlowToken"],
      "minLength": 1,
      "maxLength": 50,
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
      "type": "string"
    },
    "path": {
      "type": "object",
      "description": "The paths of the vault",
      "examples": [
        {
          "vault": "/storage/flowTokenVault",
          "balance": "/public/flowTokenBalance",
          "receiver": "/public/flowTokenReceiver"
        }
      ],
      "required": ["vault", "balance", "receiver"],
      "properties": {
        "vault": {
          "type": "string",
          "description": "The path of Provider",
          "pattern": "^/storage/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/storage/flowTokenVault"]
        },
        "balance": {
          "type": "string",
          "description": "The path of Balance",
          "pattern": "^/public/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/public/flowTokenBalance"]
        },
        "receiver": {
          "type": "string",
          "description": "The path of Receiver",
          "pattern": "^/public/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/public/flowTokenReceiver"]
        }
      },
      "additionalProperties": false
    },
    "symbol": {
      "type": "string",
      "description": "The symbol for the token; must be alphanumeric",
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
      "minLength": 1,
      "maxLength": 20,
      "examples": ["FLOW"]
    },
    "name": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
      "examples": ["Flow"]
    },
    "decimals": {
      "type": "integer",
      "description": "The number of decimals for the token balance",
      "minimum": 0,
      "maximum": 255,
      "examples": [8]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
      "format": "uri",
      "examples": [
        "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FLOW/logo.svg"
      ]
    },
    "tags": {
      "type": "array",
      "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
      "items": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "maxItems": 10,
      "examples": ["stablecoin", "compound"]
    },
    "extensions": {
      "type": "object",
      "properties": {
        "website": {
          "type": "string",
          "format": "uri"
        },
        "twitter": {
          "type": "string",
          "format": "uri"
        },
        "discord": {
          "type": "string",
          "format": "uri"
        },
        "explorer": {
          "type": "string",
          "format": "uri"
        },
        "github": {
          "type": "string",
          "format": "uri"
        },
        "medium": {
          "type": "string",
          "format": "uri"
        },
        "tgann": {
          "type": "string",
          "format": "uri"
        },
        "tggroup": {
          "type": "string",
          "format": "uri"
        },
        "address": {
          "type": "string"
        },
        "bridgeContract": {
          "type": "string"
        },
        "assetContract": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "coingeckoId": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50,
          "pattern": "^[\\-\\w]+$"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  "required": ["address", "contractName", "path", "symbol", "name", "decimals"]
}

=== FlowFans/flow-token-list/token-registry/A.231cc0dbbcffc4b7.ceUSDT/token.json
{
  "address": "0x231cc0dbbcffc4b7",
  "contractName": "ceUSDT",
  "path": {
    "vault": "/storage/ceUSDTVault",
    "balance": "/public/ceUSDTBalance",
    "receiver": "/public/ceUSDTReceiver"
  },
  "symbol": "ceUSDT",
  "name": "Tether USD (Celer)",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.231cc0dbbcffc4b7.ceUSDT/logo.png",
  "tags": ["wrapped-celer"],
  "extensions": { "coingeckoId": "tether", "website": "https://tether.to/" }
}

=== FlowFans/flow-token-list/token-registry/A.fd1ccaaae39d0e79.Mainledger/token.json
{
    "address": "0xfd1ccaaae39d0e79",
    "contractName": "Mainledger",
    "path": {
        "vault": "/storage/MainledgerVault",
        "balance": "/public/MainledgerMetadata",
        "receiver": "/public/MainledgerReceiver"
    },
    "symbol": "MLC",
    "name": "Mainledger coin",
    "decimals": 8,
    "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.fd1ccaaae39d0e79.Mainledger/logo.png",
    "tags": [
        "utility-token"
    ],
    "extensions": {}
}

=== FlowFans/flow-token-list/token-registry/A.0x231cc0dbbcffc4b7.ceBUSD/token.json
{
  "address": "0x231cc0dbbcffc4b7",
  "contractName": "ceBUSD",
  "path": {
    "vault": "/storage/ceBUSDVault",
    "balance": "/public/ceBUSDBalance",
    "receiver": "/public/ceBUSDReceiver"
  },
  "symbol": "ceBUSD",
  "name": "Binance USD (Celer)",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.0x231cc0dbbcffc4b7.ceBUSD/logo.png",
  "tags": ["wrapped-celer"],
  "extensions": {
    "address": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "assetContract": "https://bscscan.com/address/0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "coingeckoId": "binance-usd"
  }
}

=== FlowFans/flow-token-list/token-registry/A.d6f80565193ad727.stFlowToken/token.json
{
  "address": "0xd6f80565193ad727",
  "contractName": "stFlowToken",
  "path": {
    "vault": "/storage/stFlowTokenVault",
    "balance": "/public/stFlowTokenBalance",
    "receiver": "/public/stFlowTokenReceiver"
  },
  "symbol": "stFlow",
  "name": "Liquid Staked Flow",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.d6f80565193ad727.stFlowToken/logo.svg",
  "tags": ["utility-token"],
  "extensions": {
    "website": "https://app.increment.fi/staking",
    "twitter": "https://twitter.com/incrementfi",
    "discord": "https://discord.gg/r2keKxuKqX"
  }
}

=== FlowFans/flow-token-list/token-registry/A.4767b11059818832.weareliga/token.json
{
    "address": "0x4767b11059818832",
    "contractName": "weareliga",
    "path": {
      "vault": "/storage/weareligaVault",
      "balance": "/public/weareligaMetadata",
      "receiver": "/public/weareligaReceiver"
    },
    "symbol": "LIGA",
    "name": "Liga coin",
    "decimals": 8,
    "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.4767b11059818832.weareliga/logo.png",
    "tags": [
      "utility-token"
    ],
    "extensions": {
      "twitter": "https://twitter.com/Liga_TopShot"
    }
  }

=== FlowFans/flow-token-list/token-registry/A.231cc0dbbcffc4b7.ceWETH/token.json
{
  "address": "0x231cc0dbbcffc4b7",
  "contractName": "ceWETH",
  "path": {
    "vault": "/storage/ceWETHVault",
    "balance": "/public/ceWETHBalance",
    "receiver": "/public/ceWETHReceiver"
  },
  "symbol": "ceWETH",
  "name": "Wrapped Ether (Celer)",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.231cc0dbbcffc4b7.ceWETH/logo.png",
  "tags": ["wrapped-celer"],
  "extensions": { "coingeckoId": "weth" }
}

=== FlowFans/flow-token-list/token-registry/A.0x231cc0dbbcffc4b7.ceBNB/token.json
{
  "address": "0x231cc0dbbcffc4b7",
  "contractName": "ceBNB",
  "path": {
    "vault": "/storage/ceBNBVault",
    "balance": "/public/ceBNBBalance",
    "receiver": "/public/ceBNBReceiver"
  },
  "symbol": "ceBNB",
  "name": "Binance Coin (Celer)",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.0x231cc0dbbcffc4b7.ceBNB/logo.png",
  "tags": ["wrapped-celer"],
  "extensions": {
    "address": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
    "assetContract": "https://bscscan.com/address/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
    "coingeckoId": "binancecoin"
  }
}

=== FlowFans/flow-token-list/token-registry/A.88b469471cfe5535.LBJDAO/token.json
{
  "address": "0x88b469471cfe5535",
  "contractName": "LBJDAO",
  "path": {
    "vault": "/storage/LBJDAOVault",
    "balance": "/public/LBJDAOMetadata",
    "receiver": "/public/LBJDAOReceiver"
  },
  "symbol": "LBJ",
  "name": "LBJ DAO",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.88b469471cfe5535.LBJDAO/logo.png",
  "tags": [
    "utility-token"
  ],
  "extensions": {}
}
