=== FlowFans/flow-token-list/src/schemas/tokenlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "src/schemas/tokenlist",
  "title": "Flow Token List Schema",
  "description": "Schema for lists of Flow fungible tokens",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0,
          "examples": [1, 2]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0,
          "examples": [0, 1]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [0, 1]
        }
      },
      "required": ["major", "minor", "patch"]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 20,
      "pattern": "^[\\-\\w]+$",
      "examples": ["compound", "stablecoin"]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of a tag that can be associated with a token via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the tag",
          "pattern": "^[ \\-\\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the tag",
          "pattern": "^[ \\-\\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": ["name", "description"],
      "examples": [
        {
          "name": "Stablecoin",
          "description": "A token with value pegged to another asset"
        }
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "maxLength": 20,
      "pattern": "^[\\w ]+$",
      "examples": ["My Token List"]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "items": {
        "$ref": "token.schema.json"
      },
      "minItems": 1,
      "maxItems": 10000
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$",
        "examples": ["compound", "lending", "personal tokens"]
      },
      "maxItems": 20,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their name and description",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "stablecoin": {
            "name": "Stablecoin",
            "description": "A token with value pegged to another asset"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list; prefer SVG or PNG of size 256x256",
      "format": "uri",
      "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
    }
  },
  "required": ["name", "timestamp", "version", "tokens"]
}

=== FlowFans/flow-token-list/src/tokens/flow-mainnet.tokenlist.json
{
  "name": "Flow Token List",
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FLOW/logo.png",
  "keywords": [
    "flow",
    "fnt"
  ],
  "tags": {
    "stablecoin": {
      "name": "stablecoin",
      "description": "Tokens that are fixed to an external asset, e.g. the US dollar"
    },
    "ethereum": {
      "name": "ethereum",
      "description": "Asset bridged from ethereum"
    },
    "wrapped-celer": {
      "name": "wrapped-celer",
      "description": "Asset wrapped using celer bridge"
    },
    "lp-token": {
      "name": "lp-token",
      "description": "Asset representing liquidity provider token"
    },
    "nft": {
      "name": "nft",
      "description": "Non-fungible token"
    },
    "security-token": {
      "name": "security-token",
      "description": "Tokens that are used to gain access to an electronically restricted resource"
    },
    "utility-token": {
      "name": "utility-token",
      "description": "Tokens that are designed to be spent within a certain blockchain ecosystem"
    },
    "governance-token": {
      "name": "governance-token",
      "description": "Tokens that are designed to be use in community governance and maintenance"
    }
  },
  "timestamp": "2021-04-04T12:00:00+0000",
  "tokens": [
    {
      "address": "0x1654653399040a61",
      "contractName": "FlowToken",
      "path": {
        "provider":  "/storage/flowTokenVault",
        "balance":  "/public/flowTokenBalance",
        "receiver":  "/public/flowTokenReceiver"
      },
      "symbol": "FLOW",
      "name": "Flow",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FLOW/logo.svg",
      "tags": [
        "utility-token"
      ],
      "extensions": {
        "website": "https://www.onflow.org",
        "twitter": "https://twitter.com/flow_blockchain",
        "discord": "http://discord.gg/flow"
      }
    },
    {
      "address": "0x3c5959b568896393",
      "contractName": "FUSD",
      "path": {
        "provider":  "/storage/fusdVault",
        "balance":  "/public/fusdBalance",
        "receiver":  "/public/fusdReceiver"
      },
      "symbol": "FUSD",
      "name": "Flow USD",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FUSD/logo.svg",
      "tags": [
        "stablecoin"
      ],
      "extensions": {
        "website": "https://docs.onflow.org/fusd/"
      }
    },
    {
      "address": "0x0f9df91c9121c460",
      "contractName": "BloctoToken",
      "path": {
        "provider": "/storage/bloctoTokenVault",
        "balance": "/public/bloctoTokenBalance",
        "receiver": "/public/bloctoTokenReceiver"
      },
      "symbol": "BLT",
      "name": "Blocto Token",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/BLT/logo.png",
      "tags": [
        "utility-token"
      ],
      "extensions": {
        "website": "https://blocto.app/"
      }
    },
    {
      "address": "0x348fe2042c8a70d8",
      "contractName": "MyToken",
      "path": {
        "provider": "/storage/mytokenVault",
        "balance": "/public/mytokenBalance",
        "receiver": "/public/mytokenReceiver"
      },
      "symbol": "MY",
      "name": "My Token",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/MY/logo.svg",
      "tags": [
        "utility-token"
      ],
      "extensions": {
        "website": "https://mynft.io/"
      }
    },
    {
      "address": "0x142fa6570b62fd97",
      "contractName": "StarlyToken",
      "path": {
        "provider":  "/storage/starlyTokenVault",
        "balance":  "/public/starlyTokenBalance",
        "receiver":  "/public/starlyTokenReceiver"
      },
      "symbol": "STARLY",
      "name": "Starly Token",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/STARLY/logo.png",
      "tags": [
        "utility-token"
      ],
      "extensions": {
        "website": "https://starly.io/"
      }
    },
    {
      "address": "0xb19436aae4d94622",
      "contractName": "FiatToken",
      "path": {
        "provider": "/storage/USDCVault",
        "balance": "/public/USDCVaultBalance",
        "receiver": "/public/USDCVaultReceiver"
      },
      "symbol": "USDC",
      "name": "USD Coin",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/USDC/logo.svg",
      "tags": [
        "stablecoin"
      ],
      "extensions": {
        "website": "https://www.circle.com/"
      }
    }
  ],
  "version": {
    "major": 0,
    "minor": 1,
    "patch": 0
  }
}

=== FlowFans/flow-token-list/token-registry/template.tokenlist.json
{
  "name": "Flow Token List",
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.1654653399040a61.FlowToken/logo.svg",
  "keywords": ["flow", "fnt"],
  "tags": {
    "stablecoin": {
      "name": "stablecoin",
      "description": "Tokens that are fixed to an external asset, e.g. the US dollar"
    },
    "ethereum": {
      "name": "ethereum",
      "description": "Asset bridged from ethereum"
    },
    "teleported-token": {
      "name": "teleported-token",
      "description": "Asset teleported from other blockchains by Blocto"
    },
    "wrapped-celer": {
      "name": "wrapped-celer",
      "description": "Asset wrapped using celer bridge"
    },
    "lp-token": {
      "name": "lp-token",
      "description": "Asset representing liquidity provider token"
    },
    "nft": {
      "name": "nft",
      "description": "Non-fungible token"
    },
    "security-token": {
      "name": "security-token",
      "description": "Tokens that are used to gain access to an electronically restricted resource"
    },
    "utility-token": {
      "name": "utility-token",
      "description": "Tokens that are designed to be spent within a certain blockchain ecosystem"
    },
    "governance-token": {
      "name": "governance-token",
      "description": "Tokens that are designed to be use in community governance and maintenance"
    }
  },
  "timestamp": "2021-04-04T12:00:00+0000",
  "tokens": [],
  "version": {
    "major": 0,
    "minor": 1,
    "patch": 0
  }
}
