=== FlowFans/flow-token-list/src/schemas/token.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "src/schemas/token.schema.json",
  "type": "object",
  "description": "Metadata for a single token in a token list",
  "additionalProperties": false,
  "examples": [
    {
      "address": "0x1654653399040a61",
      "contractName": "FlowToken",
      "path": {
        "vault": "/storage/flowTokenVault",
        "balance": "/public/flowTokenBalance",
        "receiver": "/public/flowTokenReceiver"
      },
      "symbol": "FLOW",
      "name": "Flow",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FLOW/logo.svg",
      "tags": ["utility-token"],
      "extensions": {
        "website": "https://www.onflow.org",
        "twitter": "https://twitter.com/flow_blockchain",
        "discord": "http://discord.gg/flow"
      }
    }
  ],
  "definitions": {
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 50,
      "pattern": "^[\\-\\w]+$",
      "examples": ["compound", "stablecoin"]
    }
  },
  "properties": {
    "address": {
      "description": "The contract address",
      "examples": ["0x1654653399040a61"],
      "pattern": "^0x[0-9a-f]{16}$",
      "type": "string"
    },
    "contractName": {
      "description": "The name of the token contract",
      "examples": ["FlowToken"],
      "minLength": 1,
      "maxLength": 50,
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
      "type": "string"
    },
    "path": {
      "type": "object",
      "description": "The paths of the vault",
      "examples": [
        {
          "vault": "/storage/flowTokenVault",
          "balance": "/public/flowTokenBalance",
          "receiver": "/public/flowTokenReceiver"
        }
      ],
      "required": ["vault", "balance", "receiver"],
      "properties": {
        "vault": {
          "type": "string",
          "description": "The path of Provider",
          "pattern": "^/storage/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/storage/flowTokenVault"]
        },
        "balance": {
          "type": "string",
          "description": "The path of Balance",
          "pattern": "^/public/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/public/flowTokenBalance"]
        },
        "receiver": {
          "type": "string",
          "description": "The path of Receiver",
          "pattern": "^/public/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/public/flowTokenReceiver"]
        }
      },
      "additionalProperties": false
    },
    "symbol": {
      "type": "string",
      "description": "The symbol for the token; must be alphanumeric",
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
      "minLength": 1,
      "maxLength": 20,
      "examples": ["FLOW"]
    },
    "name": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
      "examples": ["Flow"]
    },
    "decimals": {
      "type": "integer",
      "description": "The number of decimals for the token balance",
      "minimum": 0,
      "maximum": 255,
      "examples": [8]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
      "format": "uri",
      "examples": [
        "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FLOW/logo.svg"
      ]
    },
    "tags": {
      "type": "array",
      "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
      "items": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "maxItems": 10,
      "examples": ["stablecoin", "compound"]
    },
    "extensions": {
      "type": "object",
      "properties": {
        "website": {
          "type": "string",
          "format": "uri"
        },
        "twitter": {
          "type": "string",
          "format": "uri"
        },
        "discord": {
          "type": "string",
          "format": "uri"
        },
        "explorer": {
          "type": "string",
          "format": "uri"
        },
        "github": {
          "type": "string",
          "format": "uri"
        },
        "medium": {
          "type": "string",
          "format": "uri"
        },
        "tgann": {
          "type": "string",
          "format": "uri"
        },
        "tggroup": {
          "type": "string",
          "format": "uri"
        },
        "address": {
          "type": "string"
        },
        "bridgeContract": {
          "type": "string"
        },
        "assetContract": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "coingeckoId": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50,
          "pattern": "^[\\-\\w]+$"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  "required": ["address", "contractName", "path", "symbol", "name", "decimals"]
}

=== FlowFans/flow-token-list/token-registry/FUSD/testnet.token.json
{
  "address": "0xe223d8a629e49c68",
  "contractName": "FUSD",
  "path": {
    "vault": "/storage/fusdVault",
    "balance": "/public/fusdBalance",
    "receiver": "/public/fusdReceiver"
  },
  "symbol": "FUSD",
  "name": "Flow USD",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FUSD/logo.svg",
  "tags": ["stablecoin"],
  "extensions": {
    "website": "https://docs.onflow.org/fusd/"
  }
}

=== FlowFans/flow-token-list/token-registry/A.b055bef687cfca82.TrollDAO/token.json
{
  "address": "0xb055bef687cfca82",
  "contractName": "TrollDAO",
  "path": {
    "vault": "/storage/TrollDAOVault",
    "balance": "/public/TrollDAOMetadata",
    "receiver": "/public/TrollDAOReceiver"
  },
  "symbol": "TROLL",
  "name": "Troll DAO",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.b055bef687cfca82.TrollDAO/logo.png",
  "tags": ["utility-token"],
  "extensions": {
    "twitter": "https://www.twitter.com/trollonflow"
  }
}

=== FlowFans/flow-token-list/token-registry/A.7bf07d719dcb8480.brasil/token.json
{
  "address": "0x7bf07d719dcb8480",
  "contractName": "brasil",
  "path": {
    "vault": "/storage/brasilVault",
    "balance": "/public/brasilMetadata",
    "receiver": "/public/brasilReceiver"
  },
  "symbol": "BR",
  "name": "brasil",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.7bf07d719dcb8480.brasil/logo.png",
  "tags": ["utility-token"],
  "extensions": {
    "website": "https://toucans.ecdao.org/p/brasil",
    "twitter": "https://twitter.com/flowbrasilchain",
    "discord": "https://discord.gg/hT8EpC5mUN"
  }
}

=== FlowFans/flow-token-list/token-registry/A.0x231cc0dbbcffc4b7.ceMATIC/token.json
{
  "address": "0x231cc0dbbcffc4b7",
  "contractName": "ceMATIC",
  "path": {
    "vault": "/storage/ceMATICVault",
    "balance": "/public/ceMATICBalance",
    "receiver": "/public/ceMATICReceiver"
  },
  "symbol": "ceMATIC",
  "name": "Matic Token (Celer)",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.0x231cc0dbbcffc4b7.ceMATIC/logo.png",
  "tags": ["wrapped-celer"],
  "extensions": { "coingeckoId": "matic-network" }
}

=== FlowFans/flow-token-list/token-registry/ceBNB/token.json
{
  "address": "0x231cc0dbbcffc4b7",
  "contractName": "ceBNB",
  "path": {
    "vault":"/storage/ceBNBVault",
    "balance":"/public/ceBNBBalance",
    "receiver":"/public/ceBNBReceiver"
  },
  "symbol": "BNB",
  "name": "Binance Coin",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/ceBNB/logo.png",
  "tags": [
    "wrapped-celer"
  ],
  "extensions": {
    "address": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
    "assetContract": "https://bscscan.com/address/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
    "coingeckoId": "binance-coin"
  }
}

=== FlowFans/flow-token-list/token-registry/A.cfdd90d4a00f7b5b.TeleportedTetherToken/token.json
{
  "address": "0xcfdd90d4a00f7b5b",
  "contractName": "TeleportedTetherToken",
  "path": {
    "vault": "/storage/teleportedTetherTokenVault",
    "balance": "/public/teleportedTetherTokenBalance",
    "receiver": "/public/teleportedTetherTokenReceiver"
  },
  "symbol": "tUSDT",
  "name": "Teleported Tether Token",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.cfdd90d4a00f7b5b.TeleportedTetherToken/logo.png",
  "tags": ["teleported-token", "stablecoin"],
  "extensions": { "website": "https://blocto.app/" }
}

=== FlowFans/flow-token-list/token-registry/A.475755d2c9dccc3a.TeleportedSportiumToken/token.json
{
  "address": "0x475755d2c9dccc3a",
  "contractName": "TeleportedSportiumToken",
  "path": {
    "vault": "/storage/TeleportedSportiumTokenVault",
    "balance": "/public/TeleportedSportiumTokenBalance",
    "receiver": "/public/TeleportedSportiumTokenReceiver"
  },
  "symbol": "SPRT",
  "name": "Teleported Sportium Token",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.475755d2c9dccc3a.TeleportedSportiumToken/logo.png",
  "tags": ["teleported-token"],
  "extensions": { "coingeckoId": "sportium" }
}

=== FlowFans/flow-token-list/token-registry/A.0x0f9df91c9121c460.BloctoToken/token.json
{
  "address": "0x0f9df91c9121c460",
  "contractName": "BloctoToken",
  "path": {
    "vault": "/storage/bloctoTokenVault",
    "balance": "/public/bloctoTokenBalance",
    "receiver": "/public/bloctoTokenReceiver"
  },
  "symbol": "BLT",
  "name": "Blocto Token",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.0x0f9df91c9121c460.BloctoToken/logo.png",
  "tags": ["utility-token"],
  "extensions": {
    "website": "https://blocto.app/",
    "coingeckoId": "blocto-token"
  }
}
