=== FlowFans/flow-token-list/src/schemas/token.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "src/schemas/token.schema.json",
  "type": "object",
  "description": "Metadata for a single token in a token list",
  "additionalProperties": false,
  "examples": [
    {
      "address": "0x1654653399040a61",
      "contractName": "FlowToken",
      "path": {
        "vault": "/storage/flowTokenVault",
        "balance": "/public/flowTokenBalance",
        "receiver": "/public/flowTokenReceiver"
      },
      "symbol": "FLOW",
      "name": "Flow",
      "decimals": 8,
      "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FLOW/logo.svg",
      "tags": ["utility-token"],
      "extensions": {
        "website": "https://www.onflow.org",
        "twitter": "https://twitter.com/flow_blockchain",
        "discord": "http://discord.gg/flow"
      }
    }
  ],
  "definitions": {
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 50,
      "pattern": "^[\\-\\w]+$",
      "examples": ["compound", "stablecoin"]
    }
  },
  "properties": {
    "address": {
      "description": "The contract address",
      "examples": ["0x1654653399040a61"],
      "pattern": "^0x[0-9a-f]{16}$",
      "type": "string"
    },
    "contractName": {
      "description": "The name of the token contract",
      "examples": ["FlowToken"],
      "minLength": 1,
      "maxLength": 50,
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
      "type": "string"
    },
    "path": {
      "type": "object",
      "description": "The paths of the vault",
      "examples": [
        {
          "vault": "/storage/flowTokenVault",
          "balance": "/public/flowTokenBalance",
          "receiver": "/public/flowTokenReceiver"
        }
      ],
      "required": ["vault", "balance", "receiver"],
      "properties": {
        "vault": {
          "type": "string",
          "description": "The path of Provider",
          "pattern": "^/storage/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/storage/flowTokenVault"]
        },
        "balance": {
          "type": "string",
          "description": "The path of Balance",
          "pattern": "^/public/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/public/flowTokenBalance"]
        },
        "receiver": {
          "type": "string",
          "description": "The path of Receiver",
          "pattern": "^/public/[a-zA-Z0-9+\\-%/$.]+$",
          "examples": ["/public/flowTokenReceiver"]
        }
      },
      "additionalProperties": false
    },
    "symbol": {
      "type": "string",
      "description": "The symbol for the token; must be alphanumeric",
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
      "minLength": 1,
      "maxLength": 20,
      "examples": ["FLOW"]
    },
    "name": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
      "examples": ["Flow"]
    },
    "decimals": {
      "type": "integer",
      "description": "The number of decimals for the token balance",
      "minimum": 0,
      "maximum": 255,
      "examples": [8]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
      "format": "uri",
      "examples": [
        "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/FLOW/logo.svg"
      ]
    },
    "tags": {
      "type": "array",
      "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
      "items": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "maxItems": 10,
      "examples": ["stablecoin", "compound"]
    },
    "extensions": {
      "type": "object",
      "properties": {
        "website": {
          "type": "string",
          "format": "uri"
        },
        "twitter": {
          "type": "string",
          "format": "uri"
        },
        "discord": {
          "type": "string",
          "format": "uri"
        },
        "explorer": {
          "type": "string",
          "format": "uri"
        },
        "github": {
          "type": "string",
          "format": "uri"
        },
        "medium": {
          "type": "string",
          "format": "uri"
        },
        "tgann": {
          "type": "string",
          "format": "uri"
        },
        "tggroup": {
          "type": "string",
          "format": "uri"
        },
        "address": {
          "type": "string"
        },
        "bridgeContract": {
          "type": "string"
        },
        "assetContract": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "coingeckoId": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50,
          "pattern": "^[\\-\\w]+$"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  "required": ["address", "contractName", "path", "symbol", "name", "decimals"]
}

=== FlowFans/flow-token-list/token-registry/A.1654653399040a61.FlowToken/testnet.token.json
{
  "address": "0x7e60df042a9c0868",
  "contractName": "FlowToken",
  "path": {
    "vault": "/storage/flowTokenVault",
    "balance": "/public/flowTokenBalance",
    "receiver": "/public/flowTokenReceiver"
  },
  "symbol": "FLOW",
  "name": "Flow",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.1654653399040a61.FlowToken/logo.svg",
  "tags": ["utility-token"],
  "extensions": {
    "coingeckoId": "flow",
    "website": "https://www.onflow.org",
    "twitter": "https://twitter.com/flow_blockchain",
    "discord": "http://discord.gg/flow"
  }
}

=== FlowFans/flow-token-list/token-registry/A.8259c73e487422d7.TheWolfofFlow/token.json
{
    "address": "0x8259c73e487422d7",
    "contractName": "TheWolfofFlow",
    "path": {
        "vault": "/storage/TheWolfofFlowVault",
        "balance": "/public/TheWolfofFlowMetadata",
        "receiver": "/public/TheWolfofFlowReceiver"
    },
    "symbol": "WOLF",
    "name": "The Wolf of Flow",
    "decimals": 8,
    "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.8259c73e487422d7.TheWolfofFlow/logo.png",
    "tags": [
        "utility-token"
    ],
    "extensions": {}
}

=== FlowFans/flow-token-list/token-registry/A.fd1ccaaae39d0e79.Pokertime/token.json
{
    "address": "0xfd1ccaaae39d0e79",
    "contractName": "Pokertime",
    "path": {
        "vault": "/storage/PokertimeVault",
        "balance": "/public/PokertimeMetadata",
        "receiver": "/public/PokertimeReceiver"
    },
    "symbol": "PKR",
    "name": "Poker chip",
    "decimals": 8,
    "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.fd1ccaaae39d0e79.Pokertime/logo.png",
    "tags": [
        "utility-token"
    ],
    "extensions": {}
}

=== FlowFans/flow-token-list/token-registry/A.ee09029f1dbcd9d1.TopShotBETA/token.json
{
  "address": "0xee09029f1dbcd9d1",
  "contractName": "TopShotBETA",
  "path": {
    "vault": "/storage/TopShotBETAVault",
    "balance": "/public/TopShotBETAMetadata",
    "receiver": "/public/TopShotBETAReceiver"
  },
  "symbol": "BETA",
  "name": "Top Shot BETA",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.ee09029f1dbcd9d1.TopShotBETA/logo.png",
  "tags": [
    "utility-token"
  ],
  "extensions": {}
}

=== FlowFans/flow-token-list/token-registry/A.9db94c9564243ba7.aiSportsJuice/token.json
{
    "address": "0x9db94c9564243ba7",
    "contractName": "aiSportsJuice",
    "path": {
      "vault": "/storage/aiSportsJuiceVault",
      "balance": "/public/aiSportsJuiceMetadata",
      "receiver": "/public/aiSportsJuiceReceiver"
    },
    "symbol": "JUICE",
    "name": "aiSportsJuice",
    "decimals": 8,
    "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.9db94c9564243ba7.aiSportsJuice/logo.png",
    "tags": ["utility-token"],
    "extensions": {
      "website": "https://www.aisportspro.com/",
      "twitter": "https://twitter.com/aisportspro",
      "discord": "https://discord.gg/VKvUxMwu5r"
    }
  }

=== FlowFans/flow-token-list/token-registry/A.231cc0dbbcffc4b7.ceDAI/token.json
{
  "address": "0x231cc0dbbcffc4b7",
  "contractName": "ceDAI",
  "path": {
    "vault": "/storage/ceDAIVault",
    "balance": "/public/ceDAIBalance",
    "receiver": "/public/ceDAIReceiver"
  },
  "symbol": "ceDAI",
  "name": "Dai Stablecoin (Celer)",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.231cc0dbbcffc4b7.ceDAI/logo.png",
  "tags": ["wrapped-celer"],
  "extensions": {
    "address": "0x6b175474e89094c44da98b954eedeac495271d0f",
    "assetContract": "https://etherscan.io/address/0x6b175474e89094c44da98b954eedeac495271d0f",
    "coingeckoId": "dai"
  }
}

=== FlowFans/flow-token-list/token-registry/A.e39082fc08c1cd13.THEBEARDAO/token.json
{
    "address": "0xe39082fc08c1cd13",
    "contractName": "THEBEARDAO",
    "path": {
        "vault": "/storage/THEBEARDAOVault",
        "balance": "/public/THEBEARDAOMetadata",
        "receiver": "/public/THEBEARDAOReceiver"
    },
    "symbol": "BEAR",
    "name": "THE BEAR DAO",
    "decimals": 8,
    "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.e39082fc08c1cd13.THEBEARDAO/logo.png",
    "tags": [
        "utility-token"
    ],
    "extensions": {}
}

=== FlowFans/flow-token-list/token-registry/A.231cc0dbbcffc4b7.RLY/token.json
{
  "address": "0x231cc0dbbcffc4b7",
  "contractName": "RLY",
  "path": {
    "vault": "/storage/RLYVault",
    "balance": "/public/RLYBalance",
    "receiver": "/public/RLYReceiver"
  },
  "symbol": "RLY",
  "name": "Rally",
  "decimals": 8,
  "logoURI": "https://cdn.jsdelivr.net/gh/FlowFans/flow-token-list@main/token-registry/A.231cc0dbbcffc4b7.RLY/logo.png",
  "tags": ["wrapped-celer"],
  "extensions": { "coingeckoId": "rally-2" }
}
